[package]
name = "org_domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
platform_kernel = { workspace = true }

# 第三方
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
