[package]
name = "iam_application"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# 内部
platform_kernel = { workspace = true }
iam_domain = { workspace = true }

#
futures = { workspace = true }
# 异步
async-trait = { workspace = true }
# 数据库
sqlx = { workspace = true }
# 错误
thiserror = { workspace = true }
# 工具
uuid = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
