[package]
name = "sys_application"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
platform_kernel = { workspace = true }
sys_domain = { workspace = true }

# 第三方
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }

[lints]
workspace = true
