[package]
name = "platform_middleware"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# 内部
platform_kernel = { workspace = true }
platform_config = { workspace = true }
platform_security = { workspace = true }
# 框架
axum = { workspace = true }
# 异步
tokio = { workspace = true }
# 工具
uuid = { workspace = true }
# 序列化
serde = { workspace = true }
serde_json = { workspace = true }
# 中间件
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.7", features = [
    "request-id",
    "cors",
    "compression-gzip",
    "timeout",
    "limit",
    "catch-panic",
    "set-header",
    "sensitive-headers",
    "trace",
] }
http = { version = "1.4" }
bytes = { version = "1.12" }
dashmap = { version = "6.2.1" }
futures = { workspace = true }
# 日志
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
async-trait = { workspace = true }
casbin = { workspace = true }

[lints]
workspace = true
