[package]
name = "iam_infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# 内部
platform_kernel = { workspace = true }
platform_security = { workspace = true }

iam_application = { workspace = true }
iam_domain = { workspace = true }

# 异步
tokio = { workspace = true }
async-trait = { workspace = true }
# 数据库
sqlx = { workspace = true }
# 工具
uuid = { workspace = true }
chrono = { workspace = true }
# 日志
tracing = { workspace = true }

[dev-dependencies]
argon2 = { version = "0.5" , features = ["std","rand"] }

[lints]
workspace = true
